# Generated by Django 5.1.6 on 2025-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnvioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.CharField(max_length=255)),
                ('json_entrada', models.JSONField(blank=True, null=True)),
                ('json_saida', models.JSONField(blank=True, null=True)),
                ('teste', models.CharField(choices=[('aprovacao_envio_valor_fixo', 'Aprovação de Envio de Valor Fixo'), ('aprovacao_envio_coproducao', 'Aprovação de Envio de Coprodução')], max_length=100)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=20)),
                ('mensagem', models.TextField()),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test_envio_log',
                'ordering': ['-criado_em'],
            },
        ),
    ]
