# Generated by Django 5.0 on 2025-01-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_aluno_alunoenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aluno_consultor',
            field=models.IntegerField(blank=True, db_column='alunoConsultor', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='camp_anterior',
            field=models.IntegerField(blank=True, db_column='campAnterior', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_criacao',
            field=models.DateTimeField(blank=True, db_column='dataCriacao', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_expiracao',
            field=models.DateField(blank=True, db_column='dataExpiracao', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_expiracao_7_dias',
            field=models.DateField(blank=True, db_column='dataExpiracao7Dias', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_verificacao_hotmart',
            field=models.DateTimeField(blank=True, db_column='dataVerificacaoHotmart', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email_circle',
            field=models.EmailField(blank=True, db_column='emailCircle', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='hash_user_acesso_desktop',
            field=models.CharField(blank=True, db_column='hashUserAcessoDesktop', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='hash_user_acesso_mobile',
            field=models.CharField(blank=True, db_column='hashUserAcessoMobile', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id_intercom',
            field=models.CharField(blank=True, db_column='idIntercom', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id_produto',
            field=models.CharField(blank=True, db_column='idProduto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(blank=True, db_column='nomeCompleto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_social',
            field=models.CharField(blank=True, db_column='nomeSocial', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_webhook',
            field=models.CharField(blank=True, db_column='statusWebhook', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='subscriber_code',
            field=models.CharField(blank=True, db_column='subscriberCode', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tags_interna',
            field=models.CharField(blank=True, db_column='tagsInterna', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='termo_aceito',
            field=models.IntegerField(blank=True, db_column='termoAceito', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='termo_aceito_data',
            field=models.DateTimeField(blank=True, db_column='termoAceitoData', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ultima_visita',
            field=models.DateField(blank=True, db_column='ultimaVisita', null=True),
        ),
        migrations.AlterModelTable(
            name='aluno',
            table='alunos',
        ),
    ]
