# Generated by Django 5.0 on 2025-01-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_aluno_aluno_consultor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoenvio',
            name='vinculo_aluno',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='AlunoEnvio',
        ),
    ]
