# Generated by Django 5.0 on 2025-01-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_alunoenvio_vinculo_aluno_delete_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(blank=True, db_column='nomeCompleto', max_length=255, null=True)),
                ('nomeSocial', models.CharField(blank=True, db_column='nomeSocial', max_length=255, null=True)),
                ('apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('emailCircle', models.EmailField(blank=True, db_column='emailCircle', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('csenha', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('ucode', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriberCode', models.CharField(blank=True, db_column='subscriberCode', max_length=255, null=True)),
                ('dataCriacao', models.DateTimeField(blank=True, db_column='dataCriacao', null=True)),
                ('status', models.CharField(blank=True, default='1', max_length=255, null=True)),
                ('statusWebhook', models.CharField(blank=True, db_column='statusWebhook', max_length=255, null=True)),
                ('hotmart', models.IntegerField(blank=True, null=True)),
                ('dataExpiracao', models.DateField(blank=True, db_column='dataExpiracao', null=True)),
                ('dataExpiracao7Dias', models.DateField(blank=True, db_column='dataExpiracao7Dias', null=True)),
                ('termoAceito', models.IntegerField(blank=True, db_column='termoAceito', null=True)),
                ('termoAceitoData', models.DateTimeField(blank=True, db_column='termoAceitoData', null=True)),
                ('dataVerificacaoHotmart', models.DateTimeField(blank=True, db_column='dataVerificacaoHotmart', null=True)),
                ('idProduto', models.CharField(blank=True, db_column='idProduto', max_length=255, null=True)),
                ('cla', models.IntegerField(blank=True, default=0, null=True)),
                ('nivel', models.IntegerField(blank=True, default=0, null=True)),
                ('alunoConsultor', models.IntegerField(blank=True, db_column='alunoConsultor', default=0, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('hashUserAcessoDesktop', models.CharField(blank=True, db_column='hashUserAcessoDesktop', max_length=255, null=True)),
                ('hashUserAcessoMobile', models.CharField(blank=True, db_column='hashUserAcessoMobile', max_length=255, null=True)),
                ('campAnterior', models.IntegerField(blank=True, db_column='campAnterior', default=0, null=True)),
                ('tagsInterna', models.CharField(blank=True, db_column='tagsInterna', max_length=255, null=True)),
                ('ultimaVisita', models.DateField(blank=True, db_column='ultimaVisita', null=True)),
                ('idIntercom', models.CharField(blank=True, db_column='idIntercom', max_length=255, null=True)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
    ]
