# Generated by Django 5.0 on 2025-01-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alunoenvio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoEnvio',
        ),
    ]
