# Generated by Django 5.0 on 2025-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_alunoenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoEnvio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campeonato', models.IntegerField(blank=True, null=True)),
                ('vinculoAluno', models.IntegerField(blank=True, null=True)),
                ('vinculoCliente', models.IntegerField(blank=True, null=True)),
                ('vinculoContrato', models.IntegerField(blank=True, default=0, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numeroNota', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo1', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo1Motivo', models.IntegerField(blank=True, null=True)),
                ('arquivo1Status', models.IntegerField(blank=True, default=0, null=True)),
                ('arquivo2', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo2Motivo', models.IntegerField(blank=True, null=True)),
                ('arquivo2Status', models.IntegerField(blank=True, default=0, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('textoMotivo', models.IntegerField(blank=True, null=True)),
                ('textoStatus', models.IntegerField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True, default=0, null=True)),
                ('pontoCreditado', models.IntegerField(blank=True, default=0, null=True)),
                ('pontosPreenchidos', models.IntegerField(blank=True, default=0, null=True)),
                ('pontosReais', models.IntegerField(blank=True, default=0, null=True)),
                ('desafio', models.IntegerField(blank=True, default=0, null=True)),
                ('dataCadastro', models.DateTimeField(blank=True, null=True)),
                ('rastreadorAnalise', models.IntegerField(blank=True, null=True)),
                ('dataAnalise', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('statusMotivo', models.IntegerField(blank=True, null=True)),
                ('statusComentario', models.TextField(blank=True, null=True)),
                ('statusAlteradoForcado', models.IntegerField(blank=True, default=0, null=True)),
                ('tagExcecao', models.CharField(blank=True, max_length=255, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('envioNivelInicial', models.IntegerField(blank=True, default=0, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('tipoManual', models.IntegerField(blank=True, null=True)),
                ('envioSociedade', models.IntegerField(blank=True, default=0, null=True)),
                ('vinculoCertificacao', models.IntegerField(blank=True, null=True)),
                ('vinculoCertificacaoProva', models.IntegerField(blank=True, null=True)),
                ('nivelAtualSemana', models.IntegerField(blank=True, null=True)),
                ('comentarioObservacoes', models.BinaryField(blank=True, null=True)),
                ('comentarioArquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('statusAuditoria', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'alunosenvios',
            },
        ),
    ]
