# Generated by Django 5.0 on 2025-01-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alunoenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoenvio',
            name='vinculoAluno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='users.aluno'),
            preserve_default=False,
        ),
    ]
