# Generated by Django 5.0 on 2025-01-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_alunoenvio_vinculoaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoenvio',
            name='vinculoAluno',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='AlunoEnvio',
        ),
    ]
