# Generated by Django 5.0 on 2025-01-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_aluno_alunoenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campeonato', models.IntegerField(blank=True, null=True)),
                ('aluno', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('estrangeiro', models.IntegerField(blank=True, default=0, null=True)),
                ('tipoCliente', models.IntegerField(blank=True, null=True)),
                ('tipoContrato', models.IntegerField(blank=True, null=True)),
                ('sociedade', models.IntegerField(blank=True, null=True)),
                ('porcentagemContrato', models.CharField(blank=True, max_length=255, null=True)),
                ('valorContrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vinculoEnvioCliente', models.IntegerField(blank=True, null=True)),
                ('dataContrato', models.DateField(blank=True, null=True)),
                ('clienteAntesSubidoPro', models.IntegerField(blank=True, null=True)),
                ('documentoANTIGO', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('dataCriacao', models.DateTimeField(blank=True, null=True)),
                ('rastreador', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('motivoInvalido', models.IntegerField(blank=True, null=True)),
                ('descricaoInvalido', models.TextField(blank=True, null=True)),
                ('semPontuacao', models.IntegerField(blank=True, default=0, null=True)),
                ('rastreadorAnalise', models.IntegerField(blank=True, null=True)),
                ('analiseData', models.DateTimeField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True, default=0, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('campAnterior', models.IntegerField(blank=True, default=0, null=True)),
                ('idCampAnterior', models.IntegerField(blank=True, null=True)),
                ('statusAuditoria', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'alunosclientes',
            },
        ),
    ]
