# Generated by Django 5.0 on 2025-01-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alunoclientecontrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoClienteContrato',
        ),
    ]
