# Generated by Django 5.0 on 2025-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_alunoclientecontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoClienteContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campeonato', models.IntegerField(blank=True, null=True)),
                ('aluno', models.IntegerField(blank=True, null=True)),
                ('cliente', models.IntegerField(blank=True, null=True)),
                ('tipoContrato', models.IntegerField(blank=True, null=True)),
                ('valorContrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentagemContrato', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo1', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo1S3', models.IntegerField(blank=True, default=0, null=True)),
                ('arquivo2', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo2S3', models.IntegerField(blank=True, default=0, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('dataContrato', models.DateField(blank=True, null=True)),
                ('dataVencimento', models.DateField(blank=True, null=True)),
                ('dataCriacao', models.DateTimeField(blank=True, null=True)),
                ('motivoInvalido', models.IntegerField(blank=True, null=True)),
                ('descricaoInvalido', models.TextField(blank=True, null=True)),
                ('rastreadorAnalise', models.IntegerField(blank=True, null=True)),
                ('analiseData', models.DateTimeField(blank=True, null=True)),
                ('campAnterior', models.IntegerField(blank=True, default=0, null=True)),
                ('idCampAnterior', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alunosclientescontratos',
            },
        ),
    ]
