# Generated by Django 5.0 on 2025-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alunoclientecontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoPosicaoSemana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.IntegerField(blank=True, null=True)),
                ('cla', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True, null=True)),
                ('campeonato', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alunosposicoessemana',
            },
        ),
        migrations.CreateModel(
            name='AlunoPosicaoSemanaLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.IntegerField(blank=True, null=True)),
                ('cla', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True, null=True)),
                ('campeonato', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alunosposicoessemanaLogs',
            },
        ),
    ]
