# Generated by Django 5.0 on 2025-01-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alunoposicaosemana_alunoposicaosemanalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoriaCla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('rastreador', models.IntegerField(blank=True, default=0, null=True)),
                ('rastreadorSubstituto', models.IntegerField(blank=True, default=0, null=True)),
                ('definido', models.IntegerField(blank=True, default=0, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('brasao', models.TextField(blank=True, null=True)),
                ('whatsapp', models.TextField(blank=True, null=True)),
                ('campeonato', models.IntegerField(blank=True, null=True)),
                ('idIntercom', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoriacla',
            },
        ),
    ]
