# Generated by Django 5.0 on 2025-01-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_mentoriacla'),
    ]

    operations = [
        migrations.CreateModel(
            name='alunosClientesPontosMesesRetencao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aluno', models.IntegerField(blank=True, null=True)),
                ('cliente', models.IntegerField(blank=True, null=True)),
                ('campeonato', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True, null=True)),
                ('qtdEnvios', models.IntegerField(blank=True, null=True)),
                ('idsEnvios', models.TextField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alunosclientespontosmesesretencao',
            },
        ),
    ]
