# Generated by Django 5.0 on 2025-01-22 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_alunoenvio_vinculoaluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunoenvio',
            options={'verbose_name': 'Envio do Aluno', 'verbose_name_plural': 'Envios dos Alunos'},
        ),
        migrations.AlterField(
            model_name='alunoenvio',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Pontos'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='alunoenvio',
            table=None,
        ),
        migrations.CreateModel(
            name='AjustePontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_ajustados', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pontos Ajustados')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado')], default='pendente', max_length=20, verbose_name='Status do Ajuste')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='users.alunoenvio')),
            ],
            options={
                'verbose_name': 'Ajuste de Pontos',
                'verbose_name_plural': 'Ajustes de Pontos',
            },
        ),
    ]
