# Generated by Django 5.0 on 2025-01-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_alunoenvio_options_alter_alunoenvio_pontos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustepontos',
            name='envio',
        ),
        migrations.RemoveField(
            model_name='alunoenvio',
            name='vinculoAluno',
        ),
        migrations.DeleteModel(
            name='AlunoCliente',
        ),
        migrations.DeleteModel(
            name='AlunoClienteContrato',
        ),
        migrations.DeleteModel(
            name='AlunoPosicaoSemana',
        ),
        migrations.DeleteModel(
            name='AlunoPosicaoSemanaLog',
        ),
        migrations.DeleteModel(
            name='alunosClientesPontosMesesRetencao',
        ),
        migrations.DeleteModel(
            name='MentoriaCla',
        ),
        migrations.DeleteModel(
            name='AjustePontos',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='AlunoEnvio',
        ),
    ]
