# Generated by Django 5.0 on 2025-02-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, db_column='nome_completo', max_length=255, null=True)),
                ('nome_social', models.CharField(blank=True, db_column='nome_social', max_length=255, null=True)),
                ('apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, db_column='data_criacao', null=True)),
                ('status', models.CharField(blank=True, default='1', max_length=255, null=True)),
                ('hotmart', models.IntegerField(blank=True, null=True)),
                ('termo_aceito', models.IntegerField(blank=True, db_column='termo_aceito', null=True)),
                ('cla', models.IntegerField(blank=True, default=0, null=True)),
                ('nivel', models.IntegerField(blank=True, default=0, null=True)),
                ('aluno_consultor', models.IntegerField(blank=True, db_column='aluno_consultor', default=0, null=True)),
                ('tags_interna', models.CharField(blank=True, db_column='tags_interna', max_length=255, null=True)),
            ],
        ),
    ]
