# Generated by Django 5.0 on 2025-02-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.IntegerField(blank=True, null=True)),
                ('aluno', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('estrangeiro', models.IntegerField(blank=True, default=0, null=True)),
                ('tipo_cliente', models.IntegerField(blank=True, null=True)),
                ('tipo_contrato', models.IntegerField(blank=True, null=True)),
                ('sociedade', models.IntegerField(blank=True, default=0, null=True)),
                ('cliente_antes_subidopro', models.IntegerField(blank=True, default=0, null=True)),
                ('documento_antigo', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('rastreador', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('motivo_invalido', models.IntegerField(blank=True, null=True)),
                ('descricao_invalido', models.TextField(blank=True, null=True)),
                ('sem_pontuacao', models.IntegerField(blank=True, default=0, null=True)),
                ('rastreador_analise', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
