# Generated by Django 5.0 on 2025-02-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0002_aluno_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_clientes',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='envios_aluno', to='subidometro.alunos'),
            preserve_default=False,
        ),
    ]
