# Generated by Django 5.0 on 2025-02-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0003_alter_aluno_clientes_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_clientes_contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.IntegerField(blank=True, null=True)),
                ('tipo_contrato', models.IntegerField(blank=True, null=True)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentagem_contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo1', models.CharField(blank=True, max_length=255, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('data_contrato', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_invalido', models.IntegerField(blank=True, null=True)),
                ('descricao_invalido', models.TextField(blank=True, null=True)),
                ('rastreador_analise', models.IntegerField(blank=True, null=True)),
                ('analise_data', models.DateTimeField(blank=True, null=True)),
                ('camp_anterior', models.IntegerField(default=0)),
                ('id_camp_anterior', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
