# Generated by Django 5.0 on 2025-02-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0004_aluno_clientes_contratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_clientes_contratos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='subidometro.aluno_clientes'),
            preserve_default=False,
        ),
    ]
