# Generated by Django 5.0 on 2025-02-03 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0005_alter_aluno_clientes_contratos_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_tabela', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.IntegerField(blank=True, null=True)),
                ('cliente', models.IntegerField(blank=True, null=True)),
                ('contrato', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arquivo1', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo1_motivo', models.IntegerField(blank=True, null=True)),
                ('arquivo1_status', models.IntegerField(blank=True, default=0, null=True)),
                ('desafio', models.BooleanField(default=False, verbose_name='Faz parte de um Desafio?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('rastreador_analise', models.IntegerField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('status_motivo', models.IntegerField(blank=True, null=True)),
                ('status_comentario', models.TextField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonato_envios', to='subidometro.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID do evento, envio ou desafio relacionado', null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_pontuacoes', to='subidometro.alunos')),
                ('tipo_pontuacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pontuacoes', to='subidometro.tipopontuacao')),
            ],
        ),
    ]
