# Generated by Django 5.0 on 2025-02-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0006_campeonato_tipopontuacao_aluno_envios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_envios',
            name='desafio',
        ),
    ]
