# Generated by Django 5.0 on 2025-02-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0007_remove_aluno_envios_desafio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_envios',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='envios_aluno_cl', to='subidometro.alunos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno_envios',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='envios_cliente_cl', to='subidometro.aluno_clientes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno_envios',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_contrato_cl', to='subidometro.aluno_clientes_contratos'),
        ),
    ]
