# Generated by Django 5.0 on 2025-02-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0009_desafios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_pontuacao',
            name='referencia_id',
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='certificacao',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacoes_desafios', to='subidometro.desafios'),
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacoes_envios', to='subidometro.aluno_envios'),
        ),
    ]
