# Generated by Django 5.0 on 2025-02-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0010_remove_aluno_pontuacao_referencia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafios',
            name='titulo',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
