# Generated by Django 5.0 on 2025-02-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0012_aluno_desafio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_pontuacao',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacoes_desafios', to='subidometro.aluno_desafio'),
        ),
    ]
