# Generated by Django 5.0 on 2025-02-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0013_alter_aluno_pontuacao_desafio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('rastreador_analise', models.IntegerField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('status_motivo', models.IntegerField(blank=True, null=True)),
                ('status_comentario', models.TextField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_certificacoes', to='subidometro.alunos')),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonato_certificacoes', to='subidometro.campeonato')),
            ],
        ),
    ]
