# Generated by Django 5.0 on 2025-02-03 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0014_aluno_certificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_pontuacao',
            name='certificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacoes_certificacoes', to='subidometro.aluno_certificacao'),
        ),
    ]
