# Generated by Django 5.0 on 2025-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0015_alter_aluno_pontuacao_certificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='pontos_previsto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='status_comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='status_motivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
