# Generated by Django 5.0 on 2025-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0016_aluno_pontuacao_pontos_previsto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno_pontuacao',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
