# Generated by Django 5.0 on 2025-02-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0017_aluno_pontuacao_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_pontuacao',
            name='aprovado',
        ),
    ]
