# Generated by Django 5.0 on 2025-02-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0018_remove_aluno_pontuacao_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_pontuacao',
            name='pontos_previsto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
