# Generated by Django 5.0 on 2025-02-05 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0019_alter_aluno_pontuacao_pontos_previsto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoria_cla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sigla', models.CharField(blank=True, max_length=255, null=True)),
                ('rastrador', models.IntegerField(blank=True, null=True)),
                ('rastrador_substituto', models.IntegerField(blank=True, null=True)),
                ('definido', models.IntegerField(blank=True, null=True)),
                ('brasao', models.TextField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonato_cla', to='subidometro.campeonato')),
            ],
        ),
    ]
