# Generated by Django 5.0 on 2025-02-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0020_mentoria_cla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoria_cla',
            old_name='rastrador',
            new_name='rastreador',
        ),
        migrations.RenameField(
            model_name='mentoria_cla',
            old_name='rastrador_substituto',
            new_name='rastreador_substituto',
        ),
    ]
