# Generated by Django 5.0 on 2025-02-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0021_rename_rastrador_mentoria_cla_rastreador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos_clientes_pontos_meses_retencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('pontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qtd_envios', models.IntegerField(blank=True, null=True)),
                ('ids_envios', models.CharField(blank=True, max_length=255, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunosclientespontosestemesretencao_set', to='subidometro.alunos')),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos_clientes', to='subidometro.campeonato')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunosclientespontosestemesretencao_set', to='subidometro.aluno_clientes')),
            ],
        ),
    ]
