# Generated by Django 5.0 on 2025-02-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0022_alunos_clientes_pontos_meses_retencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos_clientes_pontos_meses_retencao',
            name='ids_envios',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
