# Generated by Django 5.0 on 2025-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0023_alter_alunos_clientes_pontos_meses_retencao_ids_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_clientes',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
