# Generated by Django 5.0 on 2025-02-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0024_aluno_clientes_pontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_clientes',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonato_clientes', to='subidometro.campeonato'),
        ),
    ]
