# Generated by Django 5.0 on 2025-02-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0025_alter_aluno_clientes_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_cla', to='subidometro.mentoria_cla'),
        ),
    ]
