# Generated by Django 5.0 on 2025-02-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0026_alter_alunos_cla'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_pontuacao',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes_campeonato', to='subidometro.campeonato'),
        ),
    ]
