# Generated by Django 5.0 on 2025-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0027_aluno_pontuacao_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos_clientes_pontos_meses_retencao',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
