# Generated by Django 5.0 on 2025-02-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0028_alter_alunos_clientes_pontos_meses_retencao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campeonato',
            old_name='nome',
            new_name='identificacao',
        ),
    ]
