# Generated by Django 5.0 on 2025-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0029_rename_nome_campeonato_identificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='imagem',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campeonato',
            name='regra_PDF',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campeonato',
            name='turma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='identificacao',
            field=models.CharField(max_length=255),
        ),
    ]
