# Generated by Django 5.0 on 2025-02-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0030_campeonato_imagem_campeonato_regra_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='identificacao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='imagem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='regra_PDF',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Alunos_posicoes_semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('pontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_posicoes_semana', to='subidometro.alunos')),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_posicoes_semana_campeonato', to='subidometro.campeonato')),
                ('cla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_posicoes_semana_cla', to='subidometro.mentoria_cla')),
            ],
        ),
    ]
