# Generated by Django 5.0 on 2025-02-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0031_alter_campeonato_identificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoria_cla_posicao_semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('pontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentoria_cla_posicoes_semana_campeonato', to='subidometro.campeonato')),
                ('cla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentoria_cla_posicoes_semana_cla', to='subidometro.mentoria_cla')),
            ],
        ),
    ]
