# Generated by Django 5.0 on 2025-02-17 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0032_mentoria_cla_posicao_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos_Subidometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('nivel_motivo', models.IntegerField(blank=True, null=True)),
                ('nivel_comentario', models.TextField(blank=True, null=True)),
                ('envios', models.IntegerField(blank=True, null=True)),
                ('cliente', models.IntegerField(blank=True, null=True)),
                ('faturamento', models.IntegerField(blank=True, null=True)),
                ('faturamento_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pontuacao_geral', models.IntegerField(blank=True, null=True)),
                ('pontuacao_cla', models.IntegerField(blank=True, null=True)),
                ('rastreador', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('status_aluno', models.CharField(blank=True, max_length=255, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_subidometro', to='subidometro.alunos')),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_subidometro_campeonato', to='subidometro.campeonato')),
                ('cla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_subidometro_cla', to='subidometro.mentoria_cla')),
            ],
        ),
    ]
