# Generated by Django 5.0 on 2025-02-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0033_alunos_subidometro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campeonato',
            old_name='regra_PDF',
            new_name='regra_pdf',
        ),
    ]
