# Generated by Django 5.1.6 on 2025-02-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0034_rename_regra_pdf_campeonato_regra_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arquivo1', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo1_motivo', models.IntegerField(blank=True, null=True)),
                ('arquivo1_status', models.IntegerField(blank=True, default=0, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('rastreador_analise', models.IntegerField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('status_motivo', models.IntegerField(blank=True, null=True)),
                ('status_comentario', models.TextField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_aluno_contrato', to='subidometro.alunos')),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonato_aluno_contrato', to='subidometro.campeonato')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_aluno_contrato', to='subidometro.aluno_clientes')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato_aluno_contrato', to='subidometro.aluno_clientes_contratos')),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envio_aluno_contrato', to='subidometro.aluno_envios')),
            ],
        ),
    ]
