# Generated by Django 5.1.6 on 2025-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0035_aluno_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='arquivo1',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='arquivo1_motivo',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='arquivo1_status',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='data_analise',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='rastreador_analise',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='status',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='status_comentario',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='status_motivo',
        ),
        migrations.RemoveField(
            model_name='aluno_contrato',
            name='tipo',
        ),
        migrations.AddField(
            model_name='aluno_contrato',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno_contrato',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
