# Generated by Django 5.1.6 on 2025-02-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0036_remove_aluno_contrato_arquivo1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno_contrato',
        ),
    ]
