# Generated by Django 5.1.6 on 2025-02-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0038_aluno_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_contrato',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
