# Generated by Django 5.1.6 on 2025-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0040_aluno_certificacao_pontos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos_clientes_pontos_meses_retencao',
            name='ids_envios',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
