# Generated by Django 5.1.6 on 2025-03-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0041_alter_alunos_clientes_pontos_meses_retencao_ids_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_certificacao',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
