# Generated by Django 5.1.6 on 2025-03-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0042_aluno_certificacao_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno_pontuacao',
        ),
        migrations.DeleteModel(
            name='TipoPontuacao',
        ),
    ]
