# Generated by Django 5.1.6 on 2025-03-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0043_delete_aluno_pontuacao_delete_tipopontuacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos_posicoes_semana',
            old_name='pontos',
            new_name='pontos_totais',
        ),
    ]
