# Generated by Django 5.1.6 on 2025-03-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0045_alunos_posicoes_semana_pontos_certificacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoria_cla_posicao_semana',
            old_name='pontos',
            new_name='pontos_totais',
        ),
    ]
