# Generated by Django 5.1.6 on 2025-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0046_rename_pontos_mentoria_cla_posicao_semana_pontos_totais'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoria_cla_posicao_semana',
            name='pontos_certificacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentoria_cla_posicao_semana',
            name='pontos_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentoria_cla_posicao_semana',
            name='pontos_desafio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentoria_cla_posicao_semana',
            name='pontos_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentoria_cla_posicao_semana',
            name='pontos_recebimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentoria_cla_posicao_semana',
            name='pontos_retencao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
