# Generated by Django 5.1.6 on 2025-03-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0047_mentoria_cla_posicao_semana_pontos_certificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
