# Generated by Django 5.1.6 on 2025-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0048_campeonato_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoria_cla',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
