# Generated by Django 5.1.6 on 2025-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0049_alter_mentoria_cla_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_contrato',
            name='status',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
