# Generated by Django 5.1.6 on 2025-03-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0050_aluno_contrato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_contrato',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
