# Generated by Django 5.1.6 on 2025-03-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0051_alter_aluno_contrato_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_camp_faturamento_anterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('campeonato_turma', models.IntegerField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_camp_faturamento_anterior', to='subidometro.alunos')),
            ],
        ),
    ]
