# Generated by Django 5.1.6 on 2025-03-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0052_aluno_camp_faturamento_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos_clientes_pontos_meses_retencao',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunosclientespontosestemesretencao_set', to='subidometro.aluno_clientes_contratos'),
        ),
        migrations.AddField(
            model_name='alunos_clientes_pontos_meses_retencao',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunosclientespontosestemesretencao_set', to='subidometro.aluno_envios'),
        ),
    ]
