# Generated by Django 5.1.6 on 2025-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0053_alunos_clientes_pontos_meses_retencao_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_envios',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
