# Generated by Django 5.1.6 on 2025-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0054_aluno_envios_valor_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos_subidometro',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
