# Generated by Django 5.1.6 on 2025-04-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0054_aluno_envios_valor_calculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoria_lista_niveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('estrela', models.IntegerField(blank=True, default=1, null=True)),
                ('cor', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('checklist', models.TextField(blank=True, null=True)),
                ('ultimoNivel', models.IntegerField(blank=True, default=0, null=True)),
                ('nivelGrupo', models.IntegerField(blank=True, null=True)),
                ('idCircle', models.CharField(blank=True, max_length=255, null=True)),
                ('idIntercom', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]