# Generated by Django 5.1.6 on 2025-04-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0055_mentoria_lista_niveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoria_lista_niveis',
            old_name='ultimoNivel',
            new_name='ultimo_Nivel',
        ),
    ]
