# Generated by Django 5.1.6 on 2025-04-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0056_rename_ultimonivel_mentoria_lista_niveis_ultimo_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoria_lista_niveis',
            old_name='nivelGrupo',
            new_name='nivel_grupo',
        ),
        migrations.RenameField(
            model_name='mentoria_lista_niveis',
            old_name='ultimo_Nivel',
            new_name='ultimo_nivel',
        ),
    ]