# Generated by Django 5.1.6 on 2025-04-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0057_rename_nivelgrupo_mentoria_lista_niveis_nivel_grupo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoria_lista_niveis',
            old_name='idCircle',
            new_name='id_circle',
        ),
    ]
