# Generated by Django 5.1.6 on 2025-04-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0058_rename_idcircle_mentoria_lista_niveis_id_circle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoria_lista_niveis',
            old_name='idIntercom',
            new_name='id_intercom',
        ),
    ]