# Generated by Django 5.1.6 on 2025-04-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0055_alter_alunos_subidometro_data'),
        ('subidometro', '0059_rename_idintercom_mentoria_lista_niveis_id_intercom'),
    ]

    operations = [
    ]
