# Generated by Django 5.1.6 on 2025-07-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0060_merge_20250424_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoria_cla_posicao_semana',
            name='rastreador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Mentoria_cla_pontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentoria_cla_pontos_campeonato', to='subidometro.campeonato')),
                ('cla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentoria_cla_pontos_cla', to='subidometro.mentoria_cla')),
            ],
        ),
    ]
