# Generated by Django 5.1.6 on 2025-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0061_mentoria_cla_posicao_semana_rastreador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafios',
            name='pontos_14_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='desafios',
            name='pontos_21_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='desafios',
            name='pontos_7_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
