# Generated by Django 5.1.6 on 2025-07-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0062_desafios_pontos_14_dias_desafios_pontos_21_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_campeonato', to='subidometro.campeonato'),
        ),
    ]
