# Generated by Django 5.1.6 on 2025-08-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0063_alunos_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_nivel', to='subidometro.mentoria_lista_niveis'),
        ),
    ]
