# Generated by Django 5.1.6 on 2025-08-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subidometro', '0064_alter_alunos_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='subidometro.alunos')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='subidometro.campeonato')),
            ],
            options={
                'unique_together': {('aluno', 'campeonato')},
            },
        ),
    ]
