runtime: python310
app_engine_apis: true

instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: 'subidopro.settings'

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
    secure: always


network:
  session_affinity: true  
