
runtime: python310
app_engine_apis: true

env_variables:
  DJANGO_SETTINGS_MODULE: 'subidopro.settings'


handlers:
# directory.
- url: /static
  static_dir: static/
- url: /.*
  script: auto
  secure: always

