runtime: python
env: flex
entrypoint: gunicorn -b :$PORT subidopro.wsgi

runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.9"


# handlers:
# # directory.
# - url: /static
#   static_dir: static/
# - url: /.*
#   script: auto
#   secure: always
# - url: /ws/.*
#   script: auto
#   secure: always

