# runtime: python
# env: flex
# entrypoint: daphne -b 0.0.0.0 -p $PORT subidopro.asgi:application

# runtime_config:
#     operating_system: "ubuntu18"
#     runtime_version: "3.9"

# beta_settings:
#     cloud_sql_instances: subidopro:us-central1:db-subidopro


# handlers:
# - url: /static
#   static_files: static/\1
#   upload: static/(.*)
# - url: /ws/.*
#   script: auto
#   secure: always
# - url: /.*
#   script: auto
#   secure: always


runtime: python39
app_engine_apis: true

env_variables:
  DJANGO_SETTINGS_MODULE: 'subidopro.settings'


handlers:
# directory.
- url: /static
  static_dir: static/
- url: /.*
  script: auto
  secure: always

