# Generated by Django 5.0 on 2025-02-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], default='sucesso', max_length=10),
        ),
    ]
