# Generated by Django 5.1.6 on 2025-02-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_log_erro_log_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dados_geral',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
