payload_cliente_padrao = {
    "acao": "add",
    "codigo": "J1BGCUVI2",
    "tabela": "alunosClientes, alunosClientesContratos",
    "dataHora": "2025-04-14 17:56:33",
    "descricao": "Alterou cliente, contrato e recebimento",
        "registroAtual": {
            "alunosClientes": {
            "id": "481456",
            "aluno": "6109",
            "email": None,
            "pontos": "480",
            "semana": "6",
            "status": "0",
            "titulo": "TESTE GABRIEL RODRIGUES STALSE",
            "telefone": None,
            "descricao": None,
            "documento": "838.747.000-70",
            "sociedade": None,
            "campeonato": "6",
            "rastreador": "0",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:32",
            "estrangeiro": "0",
            "tipoCliente": "1",
            "campAnterior": "0",
            "dataContrato": None,
            "semPontuacao": "0",
            "tipoContrato": None,
            "valorContrato": None,
            "idCampAnterior": None,
            "motivoInvalido": None,
            "documentoANTIGO": None,
            "statusAuditoria": "0",
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None,
            "vinculoEnvioCliente": "0",
            "clienteAntesSubidoPro": None
        }},
    "registroAnterior": False
    }

payload_contrato_padrao = {
    "acao": "add",
    "codigo": "J1BGCUVI1",
    "tabela": "alunosClientes,alunosClientesContratos",
    "dataHora": "2025-04-14 17:56:33",
    "descricao": "Adicionou cliente, contrato e recebimento",
    "registroAtual": {
        "alunosClientes": {
            "id": "48145",
            "aluno": "6109",
            "email": None,
            "pontos": "480",
            "semana": "6",
            "status": "0",
            "titulo": "TESTE GABRIEL RODRIGUES STALSE",
            "telefone": None,
            "descricao": None,
            "documento": "838.747.000-70",
            "sociedade": None,
            "campeonato": "6",
            "rastreador": "0",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:32",
            "estrangeiro": "0",
            "tipoCliente": "1",
            "campAnterior": "0",
            "dataContrato": None,
            "semPontuacao": "0",
            "tipoContrato": None,
            "valorContrato": None,
            "idCampAnterior": None,
            "motivoInvalido": None,
            "documentoANTIGO": None,
            "statusAuditoria": "0",
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None,
            "vinculoEnvioCliente": "0",
            "clienteAntesSubidoPro": None
        },
        "alunosClientesContratos": {
            "id": "50931",
            "aluno": "6109",
            "semana": "6",
            "status": "0",
            "cliente": "48145",
            "arquivo1": "a6109-sem6-cliente-48145-contrato-2025-04-14_17-56-32.png",
            "arquivo2": None,
            "arquivo1S3": "1",
            "arquivo2S3": "0",
            "campeonato": "6",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:33",
            "campAnterior": "0",
            "dataContrato": "2008-01-18",
            "tipoContrato": "1",
            "valorContrato": "1000.00",
            "dataVencimento": "2028-03-16",
            "idCampAnterior": None,
            "motivoInvalido": None,
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None
        },
        },
    "registroAnterior": False
    }

payload_recebimento_padrao = {
    "acao": "add",
    "codigo": "J1BGCUVI1",
    "tabela": "alunosClientes,alunosClientesContratos,alunosEnvios",
    "dataHora": "2025-04-14 17:56:33",
    "descricao": "Adicionou cliente, contrato e recebimento",
    "registroAtual": {
        "alunosClientes": {
            "id": "48145",
            "aluno": "6109",
            "email": None,
            "pontos": "480",
            "semana": "6",
            "status": "0",
            "titulo": "TESTE GABRIEL RODRIGUES STALSE",
            "telefone": None,
            "descricao": None,
            "documento": "838.747.000-70",
            "sociedade": None,
            "campeonato": "6",
            "rastreador": "0",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:32",
            "estrangeiro": "0",
            "tipoCliente": "1",
            "campAnterior": "0",
            "dataContrato": None,
            "semPontuacao": "0",
            "tipoContrato": None,
            "valorContrato": None,
            "idCampAnterior": None,
            "motivoInvalido": None,
            "documentoANTIGO": None,
            "statusAuditoria": "0",
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None,
            "vinculoEnvioCliente": "0",
            "clienteAntesSubidoPro": None
        },
        "alunosClientesContratos": {
            "id": "50931",
            "aluno": "6109",
            "semana": "6",
            "status": "0",
            "cliente": "48145",
            "arquivo1": "a6109-sem6-cliente-48145-contrato-2025-04-14_17-56-32.png",
            "arquivo2": None,
            "arquivo1S3": "1",
            "arquivo2S3": "0",
            "campeonato": "6",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:33",
            "campAnterior": "0",
            "dataContrato": "2008-01-18",
            "tipoContrato": "1",
            "valorContrato": "1000.00",
            "dataVencimento": "2028-03-16",
            "idCampAnterior": None,
            "motivoInvalido": None,
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None
        },
        "alunosEnvios": {
            "id": "429870",
            "data": "2025-04-08",
            "tipo": "2",
            "texto": None,
            "valor": "1000.00",
            "pontos": "100",
            "semana": "6",
            "status": "0",
            "desafio": "0",
            "arquivo1": "a6109pv2-camp6sem6cli48145con50931-comprovantepagto-2025-04-14_17-56-33.png",
            "arquivo2": None,
            "descricao": "AQUI ESTA FUCIONANDO",
            "campeonato": "6",
            "numeroNota": None,
            "tagExcecao": None,
            "tipoManual": None,
            "dataAnalise": None,
            "pontosReais": "0",
            "textoMotivo": None,
            "textoStatus": None,
            "dataCadastro": "2025-04-14 17:56:33",
            "statusMotivo": None,
            "vinculoAluno": "6109",
            "arquivo1Motivo": None,
            "arquivo1Status": "0",
            "arquivo2Motivo": None,
            "arquivo2Status": "0",
            "envioSociedade": "0",
            "pontoCreditado": "0",
            "vinculoCliente": "48145",
            "statusAuditoria": "0",
            "valorPreenchido": "1000.00",
            "vinculoContrato": "50931",
            "nivelAtualSemana": "0",
            "statusComentario": None,
            "comentarioArquivo": None,
            "envioNivelInicial": "0",
            "pontosPreenchidos": "100",
            "rastreadorAnalise": None,
            "vinculoCertificacao": None,
            "comentarioObservacoes": None,
            "statusAlteradoForcado": "0",
            "vinculoCertificacaoProva": None
        }
    },
    "registroAnterior": False
    }

payload_desafio_padrao = {
    "acao": "add",
    "codigo": "5X84EVCYH",
    "tabela": "alunosEnvios",
    "dataHora": "2025-05-06 20:14:52",
    "descricao": "Adicionou envio de desafio",
    "registroAtual": {
    "alunosEnvios": {
        "id": "433477",
        "data": None,
        "tipo": "4",
        "texto": "https://1drv.ms/f/c/6e854a405aa58248/Esu1q0nae7FDpZO3b8UCR2oBOKxKywrEiUy13nxFquUVfw?e=uY23Sg",
        "valor": None,
        "pontos": "300",
        "semana": "9",
        "status": "0",
        "desafio": "163",
        "arquivo1": None,
        "arquivo2": None,
        "descricao": None,
        "campeonato": "6",
        "numeroNota": None,
        "tagExcecao": None,
        "tipoManual": None,
        "dataAnalise": None,
        "pontosReais": "0",
        "textoMotivo": None,
        "textoStatus": None,
        "dataCadastro": "2025-05-06 20:14:52",
        "statusMotivo": None,
        "vinculoAluno": "6109",
        "arquivo1Motivo": None,
        "arquivo1Status": "0",
        "arquivo2Motivo": None,
        "arquivo2Status": "0",
        "envioSociedade": "0",
        "pontoCreditado": "0",
        "vinculoCliente": None,
        "statusAuditoria": "0",
        "valorPreenchido": None,
        "vinculoContrato": "0",
        "nivelAtualSemana": "12",
        "statusComentario": None,
        "comentarioArquivo": None,
        "envioNivelInicial": "0",
        "pontosPreenchidos": "0",
        "rastreadorAnalise": None,
        "vinculoCertificacao": None,
        "comentarioObservacoes": None,
        "statusAlteradoForcado": "0",
        "vinculoCertificacaoProva": None
    }
    },
    "registroAnterior": False
    }

payload_certificacao_padrao = {
    "sql": False,
    "acao": "add",
    "tabela": "alunosEnvios",
    "dataHora": "2025-02-28 18:03:41",
    "registroAtual": {
    "alunosEnvios": {
        "id": "421709",
        "data": "2025-02-28",
        "tipo": "3",
        "texto": None,
        "valor": "0.00",
        "pontos": "777",
        "semana": "1",
        "status": "3",
        "desafio": "0",
        "arquivo1": None,
        "arquivo2": None,
        "descricao": "Certificação Subido de Tráfego - Google Ads | OW8HYF",
        "campeonato": "6",
        "numeroNota": None,
        "tagExcecao": None,
        "tipoManual": None,
        "dataAnalise": None,
        "pontosReais": "0",
        "textoMotivo": None,
        "textoStatus": None,
        "dataCadastro": "2025-02-28 18:03:41",
        "statusMotivo": None,
        "vinculoAluno": "6109",
        "arquivo1Motivo": None,
        "arquivo1Status": "0",
        "arquivo2Motivo": None,
        "arquivo2Status": "0",
        "envioSociedade": "0",
        "pontoCreditado": "0",
        "vinculoCliente": None,
        "statusAuditoria": "0",
        "valorPreenchido": None,
        "vinculoContrato": "0",
        "nivelAtualSemana": None,
        "statusComentario": None,
        "comentarioArquivo": None,
        "envioNivelInicial": "0",
        "pontosPreenchidos": "0",
        "rastreadorAnalise": None,
        "vinculoCertificacao": "41383",
        "comentarioObservacoes": None,
        "statusAlteradoForcado": "0",
        "vinculoCertificacaoProva": "2"
    }
    },
    "registroAnterior": False
    }

payload_campeonato_padrao = [
    {
        'id': 5,
        'identificacao': '5º Campeonato Subido PRO',
        'descricao': '',
        'data_inicio': '2024-09-01T00:00:00Z',
        'data_fim': '2025-03-03T00:00:00Z',
        'imagem': 'primeiroCampeonatoSubido.png',
        'regra_pdf': 'mentorados-regras-5-campeonato.pdf',
        'turma': 5,
        'ativo': False
    },
    {
        'id': 6,
        'identificacao': '6º Campeonato Subido PRO',
        'descricao': '',
        'data_inicio': '2024-03-11T00:00:00Z',
        'data_fim': '2025-09-07T00:00:00Z',
        'imagem': 'primeiroCampeonatoSubido.png',
        'regra_pdf': 'mentorados-regras-5-campeonato.pdf',
        'turma': 5,
        'ativo': True
    }
]

payload_desafios_padrao = [
    {
        "id": 163,
        "titulo": "Teste de Desafio fake 1",
        "descricao": "Desafio 1",
        "regras": "Regra ...",
        "data_inicio": "2025-04-14T00:00:00Z",
        "data_fim": "2025-05-14T00:00:00Z",
        "status": 0,
    },
    {
        "id": 164,
        "titulo": "Teste de Desafio fake 2",
        "descricao": "Desafio 2",
        "regras": "Regra ...",
        "data_inicio": "2025-04-14T00:00:00Z",
        "data_fim": "2025-05-14T00:00:00Z",
        "status": 0,
    }
]