payload_cliente_padrao = {
    "acao": "add",
    "codigo": "J1BGCUVI2",
    "tabela": "alunosClientes, alunosClientesContratos",
    "dataHora": "2025-04-14 17:56:33",
    "descricao": "Alterou cliente, contrato e recebimento",
        "registroAtual": {
            "alunosClientes": {
            "id": "481456",
            "aluno": "6109",
            "email": None,
            "pontos": "480",
            "semana": "6",
            "status": "0",
            "titulo": "TESTE GABRIEL RODRIGUES STALSE",
            "telefone": None,
            "descricao": None,
            "documento": "838.747.000-70",
            "sociedade": None,
            "campeonato": "6",
            "rastreador": "0",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:32",
            "estrangeiro": "0",
            "tipoCliente": "1",
            "campAnterior": "0",
            "dataContrato": None,
            "semPontuacao": "0",
            "tipoContrato": None,
            "valorContrato": None,
            "idCampAnterior": None,
            "motivoInvalido": None,
            "documentoANTIGO": None,
            "statusAuditoria": "0",
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None,
            "vinculoEnvioCliente": "0",
            "clienteAntesSubidoPro": None
        }},
    "registroAnterior": False
    }

payload_contrato_padrao = {
    "acao": "add",
    "codigo": "J1BGCUVI1",
    "tabela": "alunosClientes,alunosClientesContratos",
    "dataHora": "2025-04-14 17:56:33",
    "descricao": "Adicionou cliente, contrato e recebimento",
    "registroAtual": {
        "alunosClientes": {
            "id": "48145",
            "aluno": "6109",
            "email": None,
            "pontos": "480",
            "semana": "6",
            "status": "0",
            "titulo": "TESTE GABRIEL RODRIGUES STALSE",
            "telefone": None,
            "descricao": None,
            "documento": "838.747.000-70",
            "sociedade": None,
            "campeonato": "6",
            "rastreador": "0",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:32",
            "estrangeiro": "0",
            "tipoCliente": "1",
            "campAnterior": "0",
            "dataContrato": None,
            "semPontuacao": "0",
            "tipoContrato": None,
            "valorContrato": None,
            "idCampAnterior": None,
            "motivoInvalido": None,
            "documentoANTIGO": None,
            "statusAuditoria": "0",
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None,
            "vinculoEnvioCliente": "0",
            "clienteAntesSubidoPro": None
        },
        "alunosClientesContratos": {
            "id": "50931",
            "aluno": "6109",
            "semana": "6",
            "status": "0",
            "cliente": "48145",
            "arquivo1": "a6109-sem6-cliente-48145-contrato-2025-04-14_17-56-32.png",
            "arquivo2": None,
            "arquivo1S3": "1",
            "arquivo2S3": "0",
            "campeonato": "6",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:33",
            "campAnterior": "0",
            "dataContrato": "2008-01-18",
            "tipoContrato": "1",
            "valorContrato": "1000.00",
            "dataVencimento": "2028-03-16",
            "idCampAnterior": None,
            "motivoInvalido": None,
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None
        },
        },
    "registroAnterior": False
    }

payload_recebimento_padrao = {
    "acao": "add",
    "codigo": "J1BGCUVI1",
    "tabela": "alunosClientes,alunosClientesContratos,alunosEnvios",
    "dataHora": "2025-04-14 17:56:33",
    "descricao": "Adicionou cliente, contrato e recebimento",
    "registroAtual": {
        "alunosClientes": {
            "id": "48145",
            "aluno": "6109",
            "email": None,
            "pontos": "480",
            "semana": "6",
            "status": "0",
            "titulo": "TESTE GABRIEL RODRIGUES STALSE",
            "telefone": None,
            "descricao": None,
            "documento": "838.747.000-70",
            "sociedade": None,
            "campeonato": "6",
            "rastreador": "0",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:32",
            "estrangeiro": "0",
            "tipoCliente": "1",
            "campAnterior": "0",
            "dataContrato": None,
            "semPontuacao": "0",
            "tipoContrato": None,
            "valorContrato": None,
            "idCampAnterior": None,
            "motivoInvalido": None,
            "documentoANTIGO": None,
            "statusAuditoria": "0",
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None,
            "vinculoEnvioCliente": "0",
            "clienteAntesSubidoPro": None
        },
        "alunosClientesContratos": {
            "id": "50931",
            "aluno": "6109",
            "semana": "6",
            "status": "0",
            "cliente": "48145",
            "arquivo1": "a6109-sem6-cliente-48145-contrato-2025-04-14_17-56-32.png",
            "arquivo2": None,
            "arquivo1S3": "1",
            "arquivo2S3": "0",
            "campeonato": "6",
            "analiseData": None,
            "dataCriacao": "2025-04-14 17:56:33",
            "campAnterior": "0",
            "dataContrato": "2008-01-18",
            "tipoContrato": "1",
            "valorContrato": "1000.00",
            "dataVencimento": "2028-03-16",
            "idCampAnterior": None,
            "motivoInvalido": None,
            "descricaoInvalido": None,
            "rastreadorAnalise": None,
            "porcentagemContrato": None
        },
        "alunosEnvios": {
            "id": "429870",
            "data": "2025-04-08",
            "tipo": "2",
            "texto": None,
            "valor": "1000.00",
            "pontos": "100",
            "semana": "6",
            "status": "0",
            "desafio": "0",
            "arquivo1": "a6109pv2-camp6sem6cli48145con50931-comprovantepagto-2025-04-14_17-56-33.png",
            "arquivo2": None,
            "descricao": "AQUI ESTA FUCIONANDO",
            "campeonato": "6",
            "numeroNota": None,
            "tagExcecao": None,
            "tipoManual": None,
            "dataAnalise": None,
            "pontosReais": "0",
            "textoMotivo": None,
            "textoStatus": None,
            "dataCadastro": "2025-04-14 17:56:33",
            "statusMotivo": None,
            "vinculoAluno": "6109",
            "arquivo1Motivo": None,
            "arquivo1Status": "0",
            "arquivo2Motivo": None,
            "arquivo2Status": "0",
            "envioSociedade": "0",
            "pontoCreditado": "0",
            "vinculoCliente": "48145",
            "statusAuditoria": "0",
            "valorPreenchido": "1000.00",
            "vinculoContrato": "50931",
            "nivelAtualSemana": "0",
            "statusComentario": None,
            "comentarioArquivo": None,
            "envioNivelInicial": "0",
            "pontosPreenchidos": "100",
            "rastreadorAnalise": None,
            "vinculoCertificacao": None,
            "comentarioObservacoes": None,
            "statusAlteradoForcado": "0",
            "vinculoCertificacaoProva": None
        }
    },
    "registroAnterior": False
}

